### PR TITLE
Fix fade

### LINKED ISSUE #16: AudioParam.setTargetAtTime is broken on Chrome
- Don't use `gain.setTargetAtTime` if fade is equal to 0 (most cases)
 - Find a workaround for fading sounds (looped sounds)

### PR DESCRIPTION
**Pull request by cstoquer**
- `AudioParam.setTargetAtTime` was broken on Chrome. This function throw an error if param is less or equal to 0. We define a minimum constant to replace 0 when needed.
 - Fade system is skipped when unused.
 - We force the loading of looped sound to occur in a different thread to let garbage collector releasing the previous playing looped sound. This should help to avoid memory usage spikes when switching musics.

resolve #16

### CODE REVIEW

**Comment by cstoquer** [comment]
suggested reviewers:
@ronkorving @bchevalier

File: AudioChannel.js [hunk 1]
```diff
@@ -108,6 +108,11 @@ AudioChannel.prototype.playLoopSound = function (soundId, volume, pan, pitch) {
 		sound.play(volume * self.volume, pan, pitch); // load and play
 	}
 
+	function playNextSound() {
+		// force loading to happend in a new thread in order to let Garbage Collector to release previous audio.
```
Comment (ronkorving) [inline AudioChannel.js]: It's not a new thread, so your comment is a bit confusing.
Also *happen

Comment (ronkorving) [inline AudioChannel.js]: Also, with regards to GC, it may really help to set `this.loopSound` to null right after calling stopCurrentLoop. That would make `sound` inside `_playNextSound` the last remaining reference (if I'm not missing anything), which would hopefully cause optimistic garbage collection right after the callback of `sound.stop` has been run. You could even set `sound` to null there before calling the callback. Then there are no references left and GC *may* occur instantly.

**Comment by cstoquer** [comment]
updated

**Comment by bchevalier** [comment]
lgtm

**Comment by ronkorving** [comment]
lgtm
